import { AppShell } from "@/components/app-shell";
import { requireServerAction } from "@/lib/auth/server";
import { getPlatformHealth } from "@/lib/data/governance";

export const dynamic = "force-dynamic";

export default async function GovernancePage() {
  const session = await requireServerAction("audit:read");
  const data = await getPlatformHealth(session.tenantId);
  return (
    <AppShell title="Governance">
      <div className="pageHeader"><div><div className="eyebrow">Trust + control</div><h1 className="pageTitle">Policy is part of the product</h1><p className="pageSubtitle">Access control, auditability, retention, explanation and human review are platform primitives—not a compliance layer added after deployment.</p></div></div>
      <div className="grid metrics">
        <section className="card metric"><div className="metricLabel">Audit events loaded</div><div className="metricValue">{data.metrics.auditEvents}</div><div className="metricDelta muted">Most recent 100</div></section>
        <section className="card metric"><div className="metricLabel">Retention policies</div><div className="metricValue">{data.metrics.enabledRetentionPolicies}</div><div className="metricDelta muted">Enabled data classes</div></section>
        <section className="card metric"><div className="metricLabel">Healthy sources</div><div className="metricValue">{data.metrics.healthySources}</div><div className="metricDelta good">Connector registry</div></section>
        <section className="card metric"><div className="metricLabel">Stale / error sources</div><div className="metricValue">{data.metrics.unhealthySources}</div><div className={`metricDelta ${data.metrics.unhealthySources ? "warn" : "good"}`}>Governance attention</div></section>
      </div>
      <div className="grid twoCol">
        <section className="card cardPad"><h2 className="sectionTitle" style={{ marginBottom: 14 }}>Default controls</h2><div className="kv"><div>Tenant isolation</div><div>Every domain object carries a tenant boundary</div><div>Role authorization</div><div>Action-based RBAC with role-aware pages and server-side API checks</div><div>Audit trail</div><div>Actor, action, target, reason, before/after and request reference</div><div>Signal provenance</div><div>Rule version, evidence references and confidence</div><div>Human review</div><div>Required for high-impact interventions and Vision events</div><div>Portal relationships</div><div>Student and guardian views resolve through verified relationship records</div></div></section>
        <section className="card cardPad"><h2 className="sectionTitle" style={{ marginBottom: 14 }}>Sensitive defaults</h2><div className="emptyNote">Student and guardian portals expose restricted projections through verified self/dependent relationships. Counselor notes, staff deliberation, raw Vision footage and unrelated student information stay outside those projections.</div><div className="emptyNote" style={{ marginTop: 10 }}>Orynt Vision defaults to event metadata rather than biometric identity. Retention and snapshot storage are explicit tenant policies.</div></section>
      </div>
      <section className="card" style={{ marginTop: 16 }}><div className="sectionHead"><h2 className="sectionTitle">Retention policy registry</h2><span className="sectionMeta">Configured per data class</span></div><div className="tableWrap"><table><thead><tr><th>Data class</th><th>Retention</th><th>Basis</th><th>Enabled</th></tr></thead><tbody>{data.policies.map((policy) => <tr key={policy.id}><td className="rowLink">{policy.dataClass}</td><td>{policy.retainDays} days</td><td>{policy.legalBasis ?? "—"}</td><td>{policy.enabled ? "Yes" : "No"}</td></tr>)}</tbody></table></div></section>
      <section className="card" style={{ marginTop: 16 }}><div className="sectionHead"><h2 className="sectionTitle">Audit log</h2><span className="sectionMeta">Append-only application events</span></div>{data.audit.length ? <div className="tableWrap"><table><thead><tr><th>Time</th><th>Action</th><th>Entity</th><th>Reason</th></tr></thead><tbody>{data.audit.map((event) => <tr key={event.id}><td>{new Date(event.createdAt).toLocaleString("en-IN")}</td><td className="rowLink">{event.action}</td><td>{event.entityType}{event.entityId ? ` · ${event.entityId.slice(0,8)}` : ""}</td><td>{event.reason ?? "—"}</td></tr>)}</tbody></table></div> : <div className="signal"><div className="emptyNote">No audit events have been recorded yet.</div></div>}</section>
      <section className="card" style={{ marginTop: 16 }}><div className="sectionHead"><h2 className="sectionTitle">Role model</h2><span className="sectionMeta">Current access design</span></div><div className="tableWrap"><table><thead><tr><th>Role</th><th>Typical scope</th><th>High-impact capabilities</th></tr></thead><tbody><tr><td>Principal</td><td>School</td><td>Command, reports, interventions, governance and Vision review</td></tr><tr><td>Coordinator</td><td>Grade / classes</td><td>Academics, attendance and intervention workflows</td></tr><tr><td>Teacher</td><td>Assigned courses (scope enforcement next)</td><td>Academics, attendance and scoped interventions</td></tr><tr><td>Counselor</td><td>Assigned students (scope enforcement next)</td><td>Sensitive support context</td></tr><tr><td>IT admin</td><td>Systems</td><td>Connectors, imports, audit diagnostics</td></tr><tr><td>Student</td><td>Verified self relationship</td><td>Restricted My Progress projection</td></tr><tr><td>Parent</td><td>Verified dependent relationship</td><td>Restricted Family projection</td></tr></tbody></table></div></section>
    </AppShell>
  );
}
