import { desc, eq } from "drizzle-orm";
import { AppShell } from "@/components/app-shell";
import { EdgeAgentProvisioner } from "@/components/edge-agent-provisioner";
import { VisionReview } from "@/components/vision-review";
import { can } from "@/lib/auth/policy";
import { requireServerAction } from "@/lib/auth/server";
import { getVisionData } from "@/lib/data/vision";
import { getDb } from "@/lib/db/client";
import { edgeAgents } from "@/lib/db/frontier-schema";

export const dynamic = "force-dynamic";
export default async function VisionPage() { const session = await requireServerAction("vision:read"); const [data, agents] = await Promise.all([getVisionData(session.tenantId), getDb().select().from(edgeAgents).where(eq(edgeAgents.tenantId, session.tenantId)).orderBy(desc(edgeAgents.updatedAt)).limit(10)]); return <AppShell title="Orynt Vision"><div className="pageHeader"><div><div className="eyebrow">Safety + operations</div><h1 className="pageTitle">Edge inference, event triage, no identity graph</h1><p className="pageSubtitle">School-controlled edge software detects operational events from RTSP feeds and sends only minimal metadata to Orynt. Face recognition, emotion inference and automated discipline are outside the default product.</p></div></div><div className="grid metrics"><section className="card metric"><div className="metricLabel">Events loaded</div><div className="metricValue">{data.events.length}</div></section><section className="card metric"><div className="metricLabel">Awaiting review</div><div className="metricValue">{data.awaitingReview}</div></section><section className="card metric"><div className="metricLabel">Edge agents</div><div className="metricValue">{agents.length}</div></section><section className="card metric"><div className="metricLabel">Identity tracking</div><div className="metricValue" style={{ fontSize: 18 }}>Disabled</div></section></div><section className="card"><div className="sectionHead"><h2 className="sectionTitle">Operational event queue</h2><span className="sectionMeta">Human-reviewed metadata</span></div><div className="tableWrap"><table><thead><tr><th>Event</th><th>Zone</th><th>Camera</th><th>Confidence</th><th>Time</th><th>Status</th><th>Review</th></tr></thead><tbody>{data.events.map((e) => <tr key={e.id}><td className="rowLink">{e.eventType.replaceAll("_", " ")}</td><td>{e.zone}</td><td>{e.cameraExternalId}</td><td>{e.confidence == null ? "—" : `${Math.round(Number(e.confidence)*100)}%`}</td><td>{new Date(e.occurredAt).toLocaleString("en-IN")}</td><td><span className={`badge ${e.status}`}>{e.status}</span></td><td><VisionReview id={e.id} status={e.status}/></td></tr>)}</tbody></table></div></section><div className="grid twoCol" style={{ marginTop: 16 }}><section className="card cardPad"><h2 className="sectionTitle">Edge status</h2>{agents.length ? agents.map((agent) => <div className="signal" key={agent.id}><div className="signalTop"><div><h3>{agent.name}</h3><p>{agent.lastSeenAt ? `Last seen ${new Date(agent.lastSeenAt).toLocaleString("en-IN")}` : "Provisioned, not yet seen"}</p></div><span className={`badge ${agent.active ? "stable" : "watch"}`}>{agent.active ? "active" : "disabled"}</span></div></div>) : <div className="emptyNote">No edge host provisioned.</div>}</section>{can(session.role, "settings:write") ? <EdgeAgentProvisioner/> : <section className="card cardPad"><div className="emptyNote">Edge provisioning is restricted to platform administrators.</div></section>}</div></AppShell>; }
