import { and, eq } from "drizzle-orm";
import { NextRequest, NextResponse } from "next/server";
import { assertCan } from "@/lib/auth/policy";
import { getRequestSession } from "@/lib/auth/request";
import { connectorRequest, type ConnectorKind } from "@/lib/connectors/registry";
import { getDb } from "@/lib/db/client";
import { sourceSystems } from "@/lib/db/extended-schema";
import { connectorSyncs } from "@/lib/db/frontier-schema";

export async function POST(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { const session = await getRequestSession(request); if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); try { assertCan(session.role, "connector:manage"); } catch { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); } const { id } = await params; const db = getDb(); const [source] = await db.select().from(sourceSystems).where(and(eq(sourceSystems.id, id), eq(sourceSystems.tenantId, session.tenantId))).limit(1); if (!source) return NextResponse.json({ error: "Source not found" }, { status: 404 }); const config = (source.config ?? {}) as Record<string, unknown>; const secretRef = typeof config.secretRef === "string" ? config.secretRef : undefined; const [sync] = await db.insert(connectorSyncs).values({ tenantId: session.tenantId, sourceSystemId: source.id, entity: "students", status: "running", startedAt: new Date() }).returning(); try { const result = await connectorRequest({ kind: source.kind as ConnectorKind, baseUrl: String(config.baseUrl ?? ""), endpoint: typeof config.endpoint === "string" ? config.endpoint : undefined, token: secretRef ? process.env[secretRef] : undefined }, "students"); await db.update(connectorSyncs).set({ status: result.ok ? "completed" : "failed", rowsRead: 0, error: result.ok ? null : `HTTP ${result.status}`, completedAt: new Date() }).where(eq(connectorSyncs.id, sync.id)); await db.update(sourceSystems).set({ health: result.ok ? "healthy" : "error", lastAttemptAt: new Date(), lastSuccessfulSyncAt: result.ok ? new Date() : source.lastSuccessfulSyncAt, errorMessage: result.ok ? null : `HTTP ${result.status}`, updatedAt: new Date() }).where(eq(sourceSystems.id, source.id)); return NextResponse.json({ syncId: sync.id, ...result }); } catch (error) { const message = error instanceof Error ? error.message : "Connector failed"; await db.update(connectorSyncs).set({ status: "failed", error: message, completedAt: new Date() }).where(eq(connectorSyncs.id, sync.id)); await db.update(sourceSystems).set({ health: "error", lastAttemptAt: new Date(), errorMessage: message, updatedAt: new Date() }).where(eq(sourceSystems.id, source.id)); return NextResponse.json({ error: message }, { status: 400 }); } }
