"use client";
import { FormEvent, useState } from "react";

const catalog = [
  ["fedena", "Fedena · verified API"], ["oneroster", "OneRoster 1.2 · standard"], ["edfi", "Ed-Fi · standard"], ["teachmint-assisted", "Teachmint · assisted"], ["entab-assisted", "Entab CampusCare · assisted"], ["edunext-assisted", "Edunext · assisted"], ["generic-rest", "Generic REST · assisted"],
] as const;
export function ConnectorManager() {
  const [kind, setKind] = useState("fedena"); const [name, setName] = useState("School SIS"); const [baseUrl, setBaseUrl] = useState(""); const [endpoint, setEndpoint] = useState(""); const [token, setToken] = useState(""); const [secretRef, setSecretRef] = useState(""); const [grade, setGrade] = useState(""); const [section, setSection] = useState(""); const [result, setResult] = useState("");
  async function test(event: FormEvent) { event.preventDefault(); setResult("Testing…"); const response = await fetch("/api/connectors/test", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ kind, baseUrl, endpoint: endpoint || undefined, token: token || undefined, entity: "students" }) }); const data = await response.json(); setResult(response.ok ? `HTTP ${data.status} · ${String(data.contentType).slice(0,80)}` : data.error ?? "Failed"); }
  async function save() { setResult("Saving…"); const response = await fetch("/api/connectors/sources", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, kind, baseUrl, endpoint: endpoint || undefined, secretRef: secretRef || undefined, freshnessMinutes: 1440, mapping: { defaultGrade: grade || undefined, defaultSection: section || undefined } }) }); const data = await response.json(); setResult(response.ok ? `Saved source ${data.source.name}. Use its sync endpoint or source-health workflow to ingest.` : data.error ?? "Save failed"); }
  return <section className="card cardPad" style={{ marginTop: 16 }}><h2 className="sectionTitle">Connector workbench</h2><form onSubmit={test} style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))", gap: 10, marginTop: 14 }}><select className="searchBox" value={kind} onChange={(e) => setKind(e.target.value)}>{catalog.map(([value,label]) => <option value={value} key={value}>{label}</option>)}</select><input className="searchBox" placeholder="Source name" value={name} onChange={(e) => setName(e.target.value)}/><input className="searchBox" placeholder="https://school.example" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)}/><input className="searchBox" placeholder="Optional endpoint override" value={endpoint} onChange={(e) => setEndpoint(e.target.value)}/><input className="searchBox" type="password" placeholder="Token for one-off test" value={token} onChange={(e) => setToken(e.target.value)}/><input className="searchBox" placeholder="Secret env ref, e.g. FEDENA_TOKEN" value={secretRef} onChange={(e) => setSecretRef(e.target.value)}/><input className="searchBox" placeholder="Default grade if vendor omits it" value={grade} onChange={(e) => setGrade(e.target.value)}/><input className="searchBox" placeholder="Default section if vendor omits it" value={section} onChange={(e) => setSection(e.target.value)}/><button className="button" type="submit">Test connection</button><button className="button secondary" type="button" onClick={save}>Save source</button></form>{result ? <div className="emptyNote" style={{ marginTop: 10 }}>{result}</div> : null}</section>;
}
