"use client";

import { useMemo, useState } from "react";
import { simulateScenario } from "@/lib/domain/scenario";

export function ScenarioSimulator({ academicAverage, attendancePercent, syllabusPercent }: { academicAverage: number; attendancePercent: number; syllabusPercent: number }) {
  const [sessions, setSessions] = useState(2); const [attendanceDelta, setAttendanceDelta] = useState(2); const [syllabusDelta, setSyllabusDelta] = useState(5); const [saved, setSaved] = useState("");
  const result = useMemo(() => simulateScenario({ academicAverage, attendancePercent, syllabusPercent, remediationSessions: sessions, attendanceDeltaPp: attendanceDelta, syllabusDeltaPp: syllabusDelta }), [academicAverage, attendancePercent, syllabusPercent, sessions, attendanceDelta, syllabusDelta]);
  async function persist() { setSaved("Saving…"); const response = await fetch("/api/scenarios", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ label: `Scenario ${new Date().toLocaleDateString()}`, academicAverage, attendancePercent, syllabusPercent, remediationSessions: sessions, attendanceDeltaPp: attendanceDelta, syllabusDeltaPp: syllabusDelta }) }); const data = await response.json(); setSaved(response.ok ? `Saved ${data.id}` : data.error ?? "Save failed"); }
  return <div className="grid twoCol"><section className="card cardPad"><h2 className="sectionTitle" style={{ marginBottom: 16 }}>Scenario assumptions</h2><label style={{ display: "grid", gap: 6, marginBottom: 16, fontSize: 12 }}>Additional remediation sessions: <strong>{sessions}</strong><input type="range" min="0" max="10" step="1" value={sessions} onChange={(e) => setSessions(Number(e.target.value))}/></label><label style={{ display: "grid", gap: 6, marginBottom: 16, fontSize: 12 }}>Attendance change: <strong>{attendanceDelta > 0 ? "+" : ""}{attendanceDelta} pp</strong><input type="range" min="-10" max="10" step="1" value={attendanceDelta} onChange={(e) => setAttendanceDelta(Number(e.target.value))}/></label><label style={{ display: "grid", gap: 6, marginBottom: 16, fontSize: 12 }}>Syllabus coverage change: <strong>{syllabusDelta > 0 ? "+" : ""}{syllabusDelta} pp</strong><input type="range" min="-15" max="20" step="1" value={syllabusDelta} onChange={(e) => setSyllabusDelta(Number(e.target.value))}/></label><div className="emptyNote">Assumption-driven planning, not a causal claim. The Monte Carlo envelope perturbs transparent assumptions rather than hiding uncertainty behind a single score.</div><button className="button" style={{ marginTop: 12 }} onClick={persist}>Save scenario run</button>{saved ? <div className="muted" style={{ marginTop: 7, fontSize: 11 }}>{saved}</div> : null}</section><section className="card cardPad"><div className="eyebrow">Projected readiness</div><div style={{ fontSize: 48, fontWeight: 750, letterSpacing: "-.04em", marginTop: 8 }}>{result.estimate}</div><div className="muted" style={{ fontSize: 12 }}>Baseline {result.baseline} · p10–p90 {result.low}–{result.high}</div><div className="kv" style={{ marginTop: 22 }}><div>Model</div><div>{result.assumptions.model}</div><div>Simulation samples</div><div>{result.distribution.samples}</div><div>Remediation contribution</div><div>{result.contributions.remediation} pp</div><div>Attendance contribution</div><div>{result.contributions.attendance} pp</div><div>Syllabus contribution</div><div>{result.contributions.syllabus} pp</div></div></section></div>;
}
