"use client";
import { FormEvent, useState } from "react";

type Definition = { id: string; kind: string; key: string; name: string; description?: string | null; enabled: boolean; version: number };
export function StudioManager({ initial }: { initial: Definition[] }) {
  const [rows, setRows] = useState(initial); const [kind, setKind] = useState("metric"); const [key, setKey] = useState(""); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [message, setMessage] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/studio/definitions", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ kind, key, name, description, definition: { expression: "configure-in-studio" }, enabled: true }) }); const data = await response.json(); if (!response.ok) return setMessage(data.error ?? "Save failed"); setRows((current) => [data.definition, ...current.filter((row) => row.id !== data.definition.id)]); setMessage("Saved"); setKey(""); setName(""); setDescription(""); }
  async function remove(id: string) { const response = await fetch(`/api/studio/definitions/${id}`, { method: "DELETE" }); if (response.ok) setRows((current) => current.filter((row) => row.id !== id)); }
  return <div className="grid twoCol"><section className="card cardPad"><h2 className="sectionTitle">Create definition</h2><form onSubmit={submit} style={{ display: "grid", gap: 10, marginTop: 14 }}><select className="searchBox" value={kind} onChange={(e) => setKind(e.target.value)}><option value="object_type">Object type</option><option value="metric">Metric</option><option value="workflow">Workflow</option></select><input className="searchBox" placeholder="stable_key" value={key} onChange={(e) => setKey(e.target.value)}/><input className="searchBox" placeholder="Display name" value={name} onChange={(e) => setName(e.target.value)}/><textarea className="searchBox" placeholder="Description" value={description} onChange={(e) => setDescription(e.target.value)} rows={4}/><button className="button" type="submit">Save definition</button>{message ? <div className="muted" style={{ fontSize: 11 }}>{message}</div> : null}</form></section><section className="card cardPad"><h2 className="sectionTitle">Tenant definitions</h2><div style={{ marginTop: 12 }}>{rows.length ? rows.map((row) => <div className="signal" key={row.id}><div className="signalTop"><div><h3>{row.name}</h3><p>{row.kind} · {row.key} · v{row.version}</p></div><button className="button secondary" onClick={() => remove(row.id)}>Delete</button></div></div>) : <div className="emptyNote">No custom definitions yet.</div>}</div></section></div>;
}
