import { AppShell } from "@/components/app-shell";
import { ConnectorManager } from "@/components/connector-manager";
import { CsvImporter } from "@/components/csv-importer";
import { requireServerAction } from "@/lib/auth/server";
import { connectorCatalog } from "@/lib/connectors/registry";
import { getPlatformHealth } from "@/lib/data/governance";

export const dynamic = "force-dynamic";
export default async function ConnectPage() { const session = await requireServerAction("import:write"); const health = await getPlatformHealth(session.tenantId); return <AppShell title="Orynt Connect"><div className="pageHeader"><div><div className="eyebrow">Data plane</div><h1 className="pageTitle">Connect before you replace</h1><p className="pageSubtitle">Verified and standards-based adapters use HTTPS with tenant-scoped configuration. Secrets stay in environment/secret-manager references, not source-system records.</p></div></div><div className="grid metrics"><section className="card metric"><div className="metricLabel">Healthy sources</div><div className="metricValue">{health.metrics.healthySources}</div></section><section className="card metric"><div className="metricLabel">Stale / error</div><div className="metricValue">{health.metrics.unhealthySources}</div></section><section className="card metric"><div className="metricLabel">Imports</div><div className="metricValue">{health.imports.length}</div></section><section className="card metric"><div className="metricLabel">Catalog</div><div className="metricValue">{connectorCatalog.length}</div></section></div><ConnectorManager/><CsvImporter/><section className="card cardPad" style={{ marginTop: 16 }}><h2 className="sectionTitle">Connector catalog</h2>{connectorCatalog.map((c) => <div className="signal" key={c.kind}><div className="signalTop"><div><h3>{c.name}</h3><p>{c.note}</p></div><span className={`badge ${c.mode === "verified-api" ? "stable" : "watch"}`}>{c.mode}</span></div></div>)}</section></AppShell>; }
